import './globals.css'
import './navbar.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Image from 'next/image'
import logo from '/public/images/csa_square_logo.png'
import "@fontsource/quicksand"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'CSA@UVA',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  if (typeof window !== 'undefined') {
    // Initialize the Facebook SDK
    if (window.FB) {
      window.fbAsyncInit = function() {
        window.FB.init({
          appId: '859184232616360', 
          xfbml: true,
          version: 'v18.0',
        });
        window.FB.AppEvents.logPageView();
      };

    //   (function(d, s, id){
    //     var js, fjs = d.getElementsByTagName(s)[0];
    //     if (d.getElementById(id)) {return;}
    //     js = d.createElement(s); js.id = id;
    //     js.src = "https://connect.facebook.net/en_US/sdk.js";
    //     fjs.parentNode.insertBefore(js, fjs);
    //   }(document, 'script', 'facebook-jssdk'));
    // 
    }
  }

  return (
    <html lang="en">
        <body className={inter.className}>
          <ul id="navbar">
            {/* <Link href="/">Home</Link> */}
            <Link href="/">
              <Image src={logo} alt={'CSA'} width={80} height={80}/>
            </Link>
            <Link href="/about">About</Link>
            <div className="dropdown">
              <span className="dropdown-link">Events</span>
              <div className="dropdown-content">
                <Link href="/events/upcoming">Upcoming</Link>
                <Link href="/events/past">Past</Link>
              </div>
            </div>
            <Link href="/gallery">Gallery</Link>
          </ul>
          {children}
        </body>
    </html>
  )
}
